### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by eric-hc** [South-Paw/koa-mongoose#5]
Is there a way to interact with the db outside of koa's ctx? For instance, I want to do something like
```js
var query = {'username': req.user.username};
req.newData.username = req.user.username;

MyModel.findOneAndUpdate(query, req.newData, {upsert: true}, function(err, doc) {
    if (err) return res.send(500, {error: err});
    return res.send('Succesfully saved.');
});
```
...but I do not have access to `ctx.model` where I want to update this. Any ideas?

**Comment by South-Paw** [comment]
This is koa-middleware, so by nature you have to have the `ctx` to interact with it.

If you're wanting to interact with the database outside of the `ctx`, then I don't think this package is the right solution for that use case (I also wouldn't recommend choosing to pass the ctx around everywhere its needed either)

Unfortunately, I don't have an open source example of how I abstracted this package into it's own files in my project so that it could be used this way.

**Comment by eric-hc** [comment]
Definitely makes sense, thanks!
