### ISSUE TITLE
mongo db stream function watch(), its firing change event multiple times

### ISSUE THREAD

**Issue by manoj-negi** [South-Paw/koa-mongoose#7]
Every time I changes in my user collection, watch() getting fires change event no of time equal to no of changes. I hope you getting my or should i explain more? 

`ctx.model('users').watch().on('change', (change) => { console.log('emit'); });`

**Comment by South-Paw** [comment]
Sorry, I don't understand what the issue is here. If it's emitting things then isn't the `watch` working as intended?

Only thing issue I could see here is that since the db connection isn't being cleaned up, the watch's never end and continue streaming after a request has finished - but I'm not familiar with using mongooses `watch` and you haven't provided enough detail of the issue so I'm only making uneducated guesses at best.

To look into this further I'd need a good justification of why you believe the issue in is koa-mongoose and an example repository that reproduces the issue you're having

**Comment by manoj-negi** [comment]
> Sorry, I don't understand what the issue is here. If it's emitting things then isn't the `watch` working as intended?
> 
> Only thing issue I could see here is that since the db connection isn't being cleaned up, the watch's never end and continue streaming after a request has finished - but I'm not familiar with using mongooses `watch` and you haven't provided enough detail of the issue so I'm only making uneducated guesses at best.
> 
> To look into this further I'd need a good justification of why you believe the issue in is koa-mongoose and an example repository that reproduces the issue you're having

issue resolved. thanks for your response.
